// Copyright 2026 The Xerxes-Agents Author @erfanzar (Erfan Zare Chavoshi).
// Licensed under the Apache License, Version 2.0.

/**
 * Every desktop screen, translated from the Claude Design canvas.
 *
 * Generated by a mechanical pass over the canvas template rather than
 * hand-transcribed: `sc-for` became `.map`, `sc-if` became a conditional, and
 * `{{ }}` became an expression. 1,974 lines of markup retyped by hand would
 * carry transcription errors that only show up as a wrong screen, and the
 * design is the specification here — its copy, spacing and colour choices are
 * deliberate and are reproduced as authored.
 *
 * All values come from `buildView`, which is a pure function of the UI state.
 * Nothing in this file reaches the daemon; wiring is a separate pass.
 */

import type { ReactElement } from 'react'

import type { DesktopProps, DesktopState } from './viewModel.js'
import { buildView } from './viewModel.js'

export function Screens({
  state,
  set,
  props,
}: {
  state: DesktopState
  set: (patch: Partial<DesktopState>) => void
  props?: DesktopProps
}): ReactElement {
  const view = buildView(state, set, props ?? {}) as Record<string, any>
  const { callouts, keyHints, railOpen, mark1, mark2, mark3, theme, artLines, wordmark, nav, liveSessions, liveCount, modeLabel, windowTitle, turnBadge, isSession, isAgents, isSessions, isDiff, isTerminals, isModel, isSettings, isStyle, isIdle, isTranscript, isFanout, sessionTitle, sessionId, turnTabs, chips, tools, cards, isApproval, isTable, table, isProvider, isTools, isMcp, isAgentDefs, isCron, isPermissions, isMemory, isHistory, isStatus, isChannels, isHelp, profiles, toolRows, servers, plugins, tree, jobs, hourTicks, matrixModes, matrix, denials, tiers, weights, memFiles, timeline, ops, checks, callers, daemonOwns, helpKeys, helpCommands, approvalOptions, ledger, composer, composerHint, composerKeys, agents, agent, agentSummary, agentKeys, railRows, railIsFleet, railIsInspector, railTitle, railKey, railFoot, sessionRows, sessionSummary, sessionKeys, diffFiles, diffLines, hunkHeader, diffSummary, diffKeys, terms, term, termTail, termSummary, termKeys, providers, models, modelSummary, modelKeys, perms, modes, modeNote, runtimeRows, themes, voices, ramp, glyphs, density, statusModel, permLabel, permFg, contextLabel, statusRight, notes } = view

  return (
    <>


<div data-theme={theme} style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--x-backdrop)', color: 'var(--x-title)', fontFamily: 'var(--font-body)', fontSize: '13px', overflow: 'hidden' }}>

  <div style={{ height: '26px', flex: '0 0 26px', display: 'flex', alignItems: 'center', gap: '18px', padding: '0 14px', background: 'var(--x-menubar)', borderBottom: '1px solid var(--x-menubar-edge)', fontSize: '12.5px', color: 'var(--x-menubar-fg)' }}>
    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', color: 'var(--x-working)', fontSize: '13px' }}>✦</span>
    <span style={{ fontWeight: '600', color: 'var(--x-menubar-strong)' }}>Xerxes</span>
    <span>File</span><span>Session</span><span>Agents</span><span>Terminals</span><span>View</span><span>Window</span><span>Help</span>
    <span style={{ marginLeft: 'auto', fontFamily: '\'JetBrains Mono\', monospace', color: 'var(--x-menubar-meta)' }}>daemon v35 · connected</span>
  </div>

  <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', background: 'var(--x-screen)' }}>

    <div className="titlebar-drag" style={{ height: '40px', flex: '0 0 40px', display: 'flex', alignItems: 'center', gap: '12px', padding: '0 14px', background: 'var(--x-chrome)', borderBottom: '1px solid var(--x-hairline)' }}>
      {/* The canvas drew its own traffic lights. Real ones are used instead —
          `titleBarStyle: 'hiddenInset'` puts the working buttons exactly here —
          because painted ones look pressable and are not, and a window you
          cannot close is a worse outcome than a pixel-perfect one. This spacer
          reserves their footprint so the row's balance is unchanged. */}
      <div style={{ width: '52px', flex: '0 0 52px' }} />
      <div style={{ flex: '1 1 auto', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', fontSize: '12.5px', color: 'var(--x-secondary)' }}>
        <span style={{ fontFamily: '\'JetBrains Mono\', monospace', color: 'var(--x-working)' }}>✦</span>
        <span style={{ color: 'var(--x-title)', fontWeight: '500' }}>{windowTitle}</span>
        <span style={{ color: 'var(--x-separator)' }}>·</span>
        <span style={{ fontFamily: '\'JetBrains Mono\', monospace' }}>Xerxes-Agents</span>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: 'var(--x-meta)' }}>{turnBadge}</span>
      </div>
    </div>

    <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex' }}>

      <div style={{ width: '226px', flex: '0 0 226px', display: 'flex', flexDirection: 'column', background: 'var(--x-chrome)', borderRight: '1px solid var(--x-hairline)', overflow: 'hidden' }}>
        <div style={{ padding: '12px 12px 6px', fontSize: '10.5px', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--x-caption)', fontFamily: '\'JetBrains Mono\', monospace' }}>Screens</div>
        <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '1px', padding: '0 6px 8px' }}>
          {(nav ?? []).map((item: any, i: number) => (
           <div key={i}>
            {(item.head) ? (
              <div style={{ padding: '10px 8px 4px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', letterSpacing: '0.12em', color: 'var(--x-separator)' }}>{item.head}</div>
            ) : null}
            <div onClick={item.pick} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 8px', borderRadius: '6px', cursor: 'pointer', background: item.bg, borderLeft: `2px solid ${item.mark}` }} className={'hv1'}>
              <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: item.dot, width: '10px' }}>{item.glyph}</span>
              <span style={{ flex: '1 1 auto', fontSize: '12.5px', color: item.fg }}>{item.label}</span>
              <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', color: 'var(--x-numeric)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{item.key}</span>
            </div>
           </div>
          ))}
        </div>

        <div style={{ margin: '8px 12px 6px', fontSize: '10.5px', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--x-caption)', fontFamily: '\'JetBrains Mono\', monospace', borderTop: '1px solid var(--x-divider)', paddingTop: '10px' }}>Live · {liveCount}</div>
        <div style={{ flex: '0 0 auto', maxHeight: '104px', overflowY: 'auto', padding: '0 6px 10px', display: 'flex', flexDirection: 'column', gap: '2px' }}>
          {(liveSessions ?? []).map((s: any, i: number) => (
            <div key={i} onClick={s.pick} style={{ padding: '6px 8px', borderRadius: '6px', cursor: 'pointer', background: s.bg }} className={'hv2'}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', color: s.dot }}>●</span>
                <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-prose)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.title}</span>
              </div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', color: 'var(--x-numeric)', paddingLeft: '16px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.meta}</div>
            </div>
          ))}
        </div>

        <div style={{ borderTop: '1px solid var(--x-divider)', padding: '8px 12px', display: 'flex', alignItems: 'center', gap: '6px' }}>
          <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: 'var(--x-working)' }}>◆</span>
          <span style={{ fontSize: '12px', color: 'var(--x-secondary)' }}>{modeLabel}</span>
          <span style={{ marginLeft: 'auto', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', color: 'var(--x-numeric)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>⇥</span>
        </div>
      </div>

      <div style={{ flex: '1 1 560px', minWidth: '460px', display: 'flex', flexDirection: 'column', background: 'var(--x-screen)', overflow: 'hidden' }}>

        {(isSession) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column' }}>
            <div style={{ flex: '0 0 auto', display: 'flex', alignItems: 'center', gap: '10px', padding: '8px 16px', borderBottom: '1px solid var(--x-divider)' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)', fontWeight: '500' }}>{sessionTitle}</span>
              <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', color: 'var(--x-numeric)' }}>{sessionId}</span>
              <div style={{ marginLeft: 'auto', display: 'flex', gap: '2px', background: 'var(--x-chrome)', border: '1px solid var(--x-hairline)', borderRadius: '6px', padding: '2px' }}>
                {(turnTabs ?? []).map((t: any, i: number) => (
                  <div key={i} onClick={t.pick} style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '3px 8px', borderRadius: '4px', cursor: 'pointer', background: t.bg, fontSize: '11.5px', color: t.fg }}>
                    <span>{t.label}</span>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '9.5px', color: 'var(--x-numeric)' }}>{t.key}</span>
                  </div>
                ))}
              </div>
            </div>

            {(isIdle) ? (
              <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '22px', padding: '32px' }}>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}>
                  <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', lineHeight: '0.96' }}>
                    {(artLines ?? []).map((l: any, i: number) => (
                      <div key={i} style={{ color: l.color, whiteSpace: 'pre' }}>{l.text}</div>
                    ))}
                  </div>
                  <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '9px', lineHeight: '1' }}>
                    {(wordmark ?? []).map((w: any, i: number) => (
                      <div key={i} style={{ display: 'flex' }}>
                        {(w.cells ?? []).map((c: any, i: number) => (
                          <span key={i} style={{ color: c.color, whiteSpace: 'pre' }}>{c.text}</span>
                        ))}
                      </div>
                    ))}
                  </div>
                  <div style={{ fontSize: '12.5px', color: 'var(--x-meta)' }}>Many agents, one terminal.</div>
                </div>
                <div style={{ width: '100%', maxWidth: '560px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
                  <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)' }}>START WITH<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></div>
                  {(chips ?? []).map((c: any, i: number) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '7px 10px', border: '1px solid var(--x-hairline)', borderRadius: '8px', background: 'var(--x-card)', cursor: 'pointer' }} className={'hv3'}>
                      <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', color: 'var(--x-numeric)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 5px' }}>{c.key}</span>
                      <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12px', color: c.dot }}>{c.command}</span>
                      <span style={{ fontSize: '12.5px', color: 'var(--x-prose)' }}>{c.label}</span>
                      <span style={{ marginLeft: 'auto', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: 'var(--x-meta)' }}>{c.consequence}</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : null}

            {(isTranscript) ? (
              <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 0 18px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px', lineHeight: '1.65' }}>

                <div style={{ background: 'var(--x-working-bg)', borderLeft: '2px solid var(--x-working)', padding: '8px 16px', marginBottom: '14px' }}>
                  <div style={{ color: 'var(--x-title)' }}>Make the streaming loop cancel-safe: a cancelled turn must still leave a transcript the next provider request can accept.</div>
                </div>

                <div style={{ padding: '0 16px', color: 'var(--x-meta)', marginBottom: '10px' }}>
                  <span style={{ color: 'var(--x-caption)' }}>▾</span> thinking · cancellation repair is claimed in two places; read before changing
                </div>

                <div style={{ padding: '0 16px', display: 'flex', flexDirection: 'column', gap: '2px', marginBottom: '12px' }}>
                  {(tools ?? []).map((t: any, i: number) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                      <span style={{ color: t.dot }}>⏺</span>
                      <span style={{ color: 'var(--x-secondary)' }}>{t.verb}</span>
                      <span style={{ color: 'var(--x-prose)' }}>{t.arg}</span>
                      <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{t.leader}</span>
                      <span style={{ color: 'var(--x-numeric)' }}>{t.dur}</span>
                    </div>
                  ))}
                </div>

                <div style={{ padding: '0 16px', color: 'var(--x-prose)', maxWidth: '78ch', marginBottom: '12px' }}>
                  <span style={{ color: 'var(--x-strong)', fontWeight: '700' }}>loop.ts</span> emits the synthetic result itself, and <span style={{ color: 'var(--x-strong)', fontWeight: '700' }}>turnController</span> emits a second one for the same call. On a cancelled read the transcript ends with two results for one tool id, which the next request rejects. The repair belongs in one place: the loop owns cancellation.
                </div>

                {(isFanout) ? (
                  <div style={{ padding: '0 16px', display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '12px' }}>
                    <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)' }}>DELEGATED · 3<span style={{ color: 'var(--x-needs)' }}>{mark2}</span></div>
                    {(cards ?? []).map((c: any, i: number) => (
                      <div key={i} style={{ border: `1px solid ${c.border}`, background: c.ground, borderRadius: '8px', padding: '7px 10px' }}>
                        <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                          <span style={{ color: c.dot }}>●</span>
                          <span style={{ color: 'var(--x-title)' }}>{c.name}</span>
                          <span style={{ color: 'var(--x-separator)' }}>—</span>
                          <span style={{ color: 'var(--x-secondary)' }}>{c.task}</span>
                        </div>
                        <div style={{ paddingLeft: '16px', color: c.lineFg }}>└ {c.line}</div>
                        <div style={{ paddingLeft: '16px', color: 'var(--x-numeric)', fontSize: '11.5px' }}>{c.budget}</div>
                      </div>
                    ))}
                  </div>
                ) : null}

                {(isApproval) ? (
                  <div style={{ margin: '0 16px 12px', border: '1px solid var(--x-needs-border)', background: 'var(--x-needs-bg)', borderRadius: '8px', padding: '10px 12px' }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                      <span style={{ color: 'var(--x-needs)' }}>●</span>
                      <span style={{ color: 'var(--x-needs-text)', fontSize: '12.5px' }}>bash wants to run a command</span>
                      <span style={{ marginLeft: 'auto', fontSize: '11px', color: 'var(--x-numeric)' }}>manual · project scope</span>
                    </div>
                    <div style={{ padding: '8px 0 2px 19px', color: 'var(--x-prose)' }}>rm -rf xerxes/dist/ui &amp;&amp; bun run --cwd xerxes build:ui \</div>
                    <div style={{ padding: '0 0 8px 19px', color: 'var(--x-prose)' }}><span style={{ color: 'var(--x-numeric)' }}>↳ </span>--target bun --minify</div>
                    <div style={{ paddingLeft: '19px', fontSize: '11.5px', color: 'var(--x-meta)' }}>cwd ~/src/Xerxes-Agents · deletes 2 paths · writes 1</div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', padding: '10px 0 0 19px' }}>
                      {(approvalOptions ?? []).map((o: any, i: number) => (
                        <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '9px', fontSize: '12.5px' }}>
                          <span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '0 5px', fontSize: '10.5px' }}>{o.key}</span>
                          <span style={{ color: o.fg }}>{o.label}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ) : null}

                <div style={{ padding: '0 16px', color: 'var(--x-numeric)' }}>└ {ledger}</div>
              </div>
            ) : null}

            <div style={{ flex: '0 0 auto', borderTop: '1px solid var(--x-hairline)', background: 'var(--x-chrome)', padding: '10px 16px 8px' }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '13px' }}>
                <span style={{ color: 'var(--x-strong)' }}>❯</span>
                <span style={{ flex: '1 1 auto', color: 'var(--x-prose)' }}>{composer}<span style={{ color: 'var(--x-working)', animation: 'nxpulse 1.1s infinite' }}>▍</span></span>
                <span style={{ fontSize: '10.5px', color: 'var(--x-numeric)' }}>{composerHint}<span style={{ color: 'var(--x-needs)' }}>{mark3}</span></span>
              </div>
              {(keyHints) ? (
                <div style={{ display: 'flex', gap: '14px', marginTop: '8px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', color: 'var(--x-caption)' }}>
                  {(composerKeys ?? []).map((k: any, i: number) => (
                    <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
                  ))}
                </div>
              ) : null}
            </div>
          </div>
        ) : null}

        {(isAgents) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>Agents</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{agentSummary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>grouped by what you must do<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '8px 10px' }}>
              {(agents ?? []).map((a: any, i: number) => (
                <div key={i}>
                  {(a.heading) ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 6px 5px' }}>
                      <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: a.headFg }}>{a.heading}</span>
                      <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                    </div>
                  ) : null}
                  <div onClick={a.pick} style={{ border: `1px solid ${a.border}`, background: a.ground, borderRadius: '8px', padding: '7px 10px', marginBottom: '4px', cursor: 'pointer', borderLeft: `3px solid ${a.rail}` }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                      <span style={{ fontSize: '11px', color: a.dot }}>●</span>
                      <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{a.name}</span>
                      <span style={{ color: 'var(--x-separator)' }}>—</span>
                      <span style={{ fontSize: '12px', color: 'var(--x-secondary)' }}>{a.task}</span>
                      <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{a.leader}</span>
                      <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{a.budget}</span>
                    </div>
                    <div style={{ paddingLeft: '19px', fontSize: '12px', color: a.lineFg }}>└ {a.line}</div>
                  </div>
                </div>
              ))}
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(agentKeys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isSessions) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>Chats</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{sessionSummary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>detached chats keep working<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '8px 10px' }}>
              {(sessionRows ?? []).map((s: any, i: number) => (
                <div key={i}>
                  {(s.heading) ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 6px 5px' }}>
                      <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: s.headFg }}>{s.heading}</span>
                      <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                    </div>
                  ) : null}
                  <div onClick={s.pick} style={{ display: 'flex', alignItems: 'baseline', gap: '8px', padding: '5px 8px', borderRadius: '6px', cursor: 'pointer', background: s.bg }} className={'hv4'}>
                    <span style={{ fontSize: '11px', color: s.dot }}>●</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{s.title}</span>
                    <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{s.leader}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{s.age}</span>
                  </div>
                  <div style={{ padding: '0 8px 3px 27px', fontSize: '12px', color: s.lineFg }}>{s.line}</div>
                </div>
              ))}
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(sessionKeys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isDiff) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>working tree</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{diffSummary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>cyan is a fold boundary, never a state<span style={{ color: 'var(--x-needs)' }}>{mark2}</span></span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex' }}>
              <div style={{ width: '250px', flex: '0 0 250px', borderRight: '1px solid var(--x-divider)', padding: '8px 8px', overflowY: 'auto' }}>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '2px 6px 6px' }}>FILES · 3<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></div>
                {(diffFiles ?? []).map((f: any, i: number) => (
                  <div key={i} onClick={f.pick} style={{ padding: '5px 6px', borderRadius: '6px', cursor: 'pointer', background: f.bg }} className={'hv5'}>
                    <div style={{ fontSize: '12px', color: 'var(--x-prose)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', direction: 'rtl', textAlign: 'left' }}>{f.path}</div>
                    <div style={{ fontSize: '11px', display: 'flex', gap: '8px', paddingTop: '1px' }}>
                      <span style={{ color: 'var(--x-done)' }}>{f.add}</span>
                      <span style={{ color: 'var(--x-failed)' }}>{f.del}</span>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ flex: '1 1 auto', minWidth: '0', overflow: 'auto', padding: '8px 0' }}>
                <div style={{ padding: '4px 14px', background: 'var(--x-diff-hunk)', color: 'var(--x-structure)', fontSize: '12px' }}>{hunkHeader}</div>
                {(diffLines ?? []).map((l: any, i: number) => (
                  <div key={i} style={{ display: 'flex', background: l.bg, fontSize: '12.5px', lineHeight: '1.6' }}>
                    <span style={{ width: '52px', flex: '0 0 52px', textAlign: 'right', paddingRight: '10px', color: 'var(--x-separator)' }}>{l.no}</span>
                    <span style={{ width: '14px', flex: '0 0 14px', color: l.signFg }}>{l.sign}</span>
                    <span style={{ color: l.fg, whiteSpace: 'pre' }}>{l.text}</span>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(diffKeys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isTerminals) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>Terminals</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{termSummary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>watching reads a mirror, never the agent's buffer<span style={{ color: 'var(--x-needs)' }}>{mark2}</span></span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex' }}>
              <div style={{ width: '320px', flex: '0 0 320px', borderRight: '1px solid var(--x-divider)', overflowY: 'auto', padding: '8px 8px' }}>
                {(terms ?? []).map((t: any, i: number) => (
                  <div key={i}>
                    {(t.heading) ? (
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 6px 4px' }}>
                        <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: t.headFg }}>{t.heading}</span>
                        <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                      </div>
                    ) : null}
                    <div onClick={t.pick} style={{ padding: '5px 6px', borderRadius: '6px', cursor: 'pointer', background: t.bg }} className={'hv6'}>
                      <div style={{ display: 'flex', alignItems: 'baseline', gap: '7px' }}>
                        <span style={{ fontSize: '11px', color: t.dot }}>●</span>
                        <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-prose)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{t.cmd}</span>
                      </div>
                      <div style={{ paddingLeft: '18px', fontSize: '11px', color: 'var(--x-numeric)' }}>{t.meta}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ flex: '1 1 auto', minWidth: '0', display: 'flex', flexDirection: 'column' }}>
                <div style={{ padding: '8px 14px', borderBottom: '1px solid var(--x-divider)' }}>
                  <div style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{term.cmd}</div>
                  <div style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{term.detail}</div>
                </div>
                <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '8px 14px', background: 'var(--x-sunken)', fontSize: '12.5px', lineHeight: '1.6' }}>
                  {(termTail ?? []).map((l: any, i: number) => (
                    <div key={i} style={{ color: l.fg, whiteSpace: 'pre-wrap' }}>{l.text}</div>
                  ))}
                </div>
              </div>
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(termKeys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isModel) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/model</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{modelSummary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>an offline backend says so instead of failing later<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex' }}>
              <div style={{ width: '220px', flex: '0 0 220px', borderRight: '1px solid var(--x-divider)', padding: '8px', overflowY: 'auto' }}>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '2px 6px 6px' }}>PROVIDERS</div>
                {(providers ?? []).map((p: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '7px', padding: '5px 6px', borderRadius: '6px', background: p.bg, cursor: 'pointer' }} className={'hv7'}>
                    <span style={{ fontSize: '11px', color: p.dot }}>●</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-prose)' }}>{p.name}</span>
                    <span style={{ fontSize: '10.5px', color: 'var(--x-numeric)' }}>{p.state}</span>
                  </div>
                ))}
              </div>
              <div style={{ flex: '1 1 auto', minWidth: '0', overflowY: 'auto', padding: '10px 14px' }}>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '6px' }}>MODELS · anthropic</div>
                {(models ?? []).map((m: any, i: number) => (
                  <div key={i} onClick={m.pick} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '7px 10px', border: `1px solid ${m.border}`, background: m.bg, borderRadius: '8px', marginBottom: '4px', cursor: 'pointer' }}>
                    <span style={{ fontSize: '11px', color: m.dot }}>{m.glyph}</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{m.name}</span>
                    <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{m.leader}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{m.meta}</span>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(modelKeys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isSettings) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '18px 22px', display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '720px' }}>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>PERMISSION MODE<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {(perms ?? []).map((p: any, i: number) => (
                  <div key={i} onClick={p.pick} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '8px 11px', border: `1px solid ${p.border}`, background: p.bg, borderRadius: '8px', cursor: 'pointer' }}>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: p.dot }}>{p.glyph}</span>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px', color: 'var(--x-title)', width: '96px' }}>{p.name}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12.5px', color: 'var(--x-secondary)' }}>{p.note}</span>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10px', color: 'var(--x-numeric)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 5px' }}>{p.key}</span>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>INTERACTION MODE</div>
              <div style={{ display: 'flex', gap: '6px' }}>
                {(modes ?? []).map((m: any, i: number) => (
                  <div key={i} onClick={m.pick} style={{ display: 'flex', alignItems: 'center', gap: '7px', padding: '7px 12px', border: `1px solid ${m.border}`, background: m.bg, borderRadius: '8px', cursor: 'pointer' }}>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: m.dot }}>◆</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{m.name}</span>
                  </div>
                ))}
              </div>
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '7px' }}>{modeNote}</div>
            </div>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>PALETTE</div>
              <div style={{ display: 'flex', gap: '6px' }}>
                {(themes ?? []).map((t: any, i: number) => (
                  <div key={i} onClick={t.pick} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '7px 12px', border: `1px solid ${t.border}`, background: t.bg, borderRadius: '8px', cursor: 'pointer' }}>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: t.dot }}>{t.glyph}</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{t.name}</span>
                    <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', color: 'var(--x-numeric)' }}>{t.note}</span>
                  </div>
                ))}
              </div>
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '7px', maxWidth: '68ch', textWrap: 'pretty' }}>Auto follows the terminal's own background query rather than guessing from the environment. XERXES_TUI_THEME pins it and the probe will not fight the pin.</div>
            </div>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>RUNTIME</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px' }}>
                {(runtimeRows ?? []).map((r: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '5px 2px' }}>
                    <span style={{ color: 'var(--x-secondary)', width: '168px' }}>{r.label}</span>
                    <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{r.leader}</span>
                    <span style={{ color: 'var(--x-prose)' }}>{r.value}</span>
                  </div>
                ))}
              </div>
              <div style={{ display: 'flex', gap: '8px', paddingTop: '14px' }}>
                <button className={'btn btn-secondary'} type={'button'}>Run doctor</button>
                <button className={'btn btn-ghost'} type={'button'}>Reload MCP servers</button>
              </div>
            </div>
          </div>
        ) : null}

        {(isStyle) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '18px 22px 30px', display: 'flex', flexDirection: 'column', gap: '22px' }}>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '4px' }}>SIX VOICES<span style={{ color: 'var(--x-needs)' }}>{mark1}</span></div>
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingBottom: '10px', maxWidth: '62ch' }}>Each colour owns exactly one meaning product-wide. A screen where nothing is blocked carries no amber at all.</div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(212px, 1fr))', gap: '8px' }}>
                {(voices ?? []).map((v: any, i: number) => (
                  <div key={i} style={{ border: '1px solid var(--x-hairline)', borderRadius: '8px', padding: '9px 11px', background: 'var(--x-card)' }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px', fontFamily: '\'JetBrains Mono\', monospace' }}>
                      <span style={{ fontSize: '12px', color: v.hex }}>●</span>
                      <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{v.name}</span>
                      <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-numeric)' }}>{v.hex}</span>
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--x-secondary)', paddingTop: '3px' }}>{v.means}</div>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '10px' }}>TEXT RAMP · eight steps, assigned by role</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px' }}>
                {(ramp ?? []).map((r: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '3px 2px' }}>
                    <span style={{ color: r.hex, width: '96px' }}>{r.name}</span>
                    <span style={{ color: r.hex, flex: '1 1 auto' }}>{r.sample}</span>
                    <span style={{ color: 'var(--x-separator)', fontSize: '10.5px' }}>{r.hex}</span>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ display: 'flex', gap: '22px', flexWrap: 'wrap' }}>
              <div style={{ flex: '1 1 300px' }}>
                <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '10px' }}>GLYPHS · one glyph, one job</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px' }}>
                  {(glyphs ?? []).map((g: any, i: number) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '12px' }}>
                      <span style={{ color: 'var(--x-prose)', width: '18px', textAlign: 'center' }}>{g.glyph}</span>
                      <span style={{ color: 'var(--x-secondary)' }}>{g.job}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div style={{ flex: '1 1 300px' }}>
                <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '10px' }}>GIVEN UP FIRST AS THE WINDOW NARROWS<span style={{ color: 'var(--x-needs)' }}>{mark2}</span></div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '12.5px' }}>
                  {(density ?? []).map((d: any, i: number) => (
                    <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px' }}>
                      <span style={{ color: 'var(--x-numeric)', width: '22px' }}>{d.n}</span>
                      <span style={{ color: 'var(--x-prose)', flex: '1 1 auto' }}>{d.what}</span>
                      <span style={{ color: 'var(--x-numeric)' }}>{d.at}</span>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '10px', maxWidth: '52ch' }}>Titles and state dots never go. The composer and the approval card never degrade at all.</div>
              </div>
            </div>
          </div>
        ) : null}

        {(isTable) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{table.title}</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>{table.summary}</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>{table.note}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '4px 12px 14px' }}>
              {(table.rows ?? []).map((r: any, i: number) => (
                <div key={i}>
                  {(r.heading) ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 2px 5px' }}>
                      <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: r.headFg }}>{r.heading}</span>
                      <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                    </div>
                  ) : null}
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '9px', padding: '3px 2px' }}>
                    <span style={{ fontSize: '11px', color: r.dot, width: '9px' }}>{r.glyph}</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{r.name}</span>
                    <span style={{ fontSize: '12px', color: 'var(--x-secondary)' }}>{r.sub}</span>
                    <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{r.leader}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{r.right}</span>
                  </div>
                  {(r.line) ? (
                    <div style={{ padding: '0 2px 3px 20px', fontSize: '12px', color: r.lineFg }}>{r.line}</div>
                  ) : null}
                </div>
              ))}
              {(table.foot) ? (
                <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', padding: '16px 2px 0', maxWidth: '66ch', textWrap: 'pretty' }}>{table.foot}</div>
              ) : null}
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              {(table.keys ?? []).map((k: any, i: number) => (
                <span key={i}><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{k.key}</span> {k.label}</span>
              ))}
            </div>
          </div>
        ) : null}

        {(isProvider) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px', fontFamily: '\'JetBrains Mono\', monospace' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/provider</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>3 profiles · 1 unreachable</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>credentials stay outside the repository{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px', display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(268px, 1fr))', gap: '10px', alignContent: 'start' }}>
              {(profiles ?? []).map((p: any, i: number) => (
                <div key={i} style={{ border: `1px solid ${p.border}`, background: p.ground, borderRadius: '8px', padding: '12px', display: 'flex', flexDirection: 'column', gap: '9px' }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px', fontFamily: '\'JetBrains Mono\', monospace' }}>
                    <span style={{ fontSize: '11px', color: p.dot }}>●</span>
                    <span style={{ fontSize: '13px', color: 'var(--x-strong)' }}>{p.name}</span>
                    <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: p.dot }}>{p.badge}</span>
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '3px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11.5px' }}>
                    <div style={{ display: 'flex', gap: '8px' }}><span style={{ color: 'var(--x-caption)', width: '74px' }}>provider</span><span style={{ color: 'var(--x-prose)' }}>{p.provider}</span></div>
                    <div style={{ display: 'flex', gap: '8px' }}><span style={{ color: 'var(--x-caption)', width: '74px' }}>model</span><span style={{ color: 'var(--x-prose)' }}>{p.model}</span></div>
                    <div style={{ display: 'flex', gap: '8px' }}><span style={{ color: 'var(--x-caption)', width: '74px' }}>credential</span><span style={{ color: p.credFg }}>{p.credential}</span></div>
                    <div style={{ display: 'flex', gap: '8px' }}><span style={{ color: 'var(--x-caption)', width: '74px' }}>base URL</span><span style={{ color: 'var(--x-secondary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{p.baseUrl}</span></div>
                  </div>
                  <div style={{ fontSize: '11.5px', color: p.noteFg, borderTop: '1px solid var(--x-divider)', paddingTop: '8px', textWrap: 'pretty' }}>{p.note}</div>
                </div>
              ))}
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>⏎</span> select</span>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>n</span> new profile</span>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>t</span> test connection</span>
            </div>
          </div>
        ) : null}

        {(isTools) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/tools</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>19 groups · 7 awaiting a host port</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>a missing port errors rather than simulating{mark1}</span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'minmax(84px, 146px) minmax(0, 1fr) minmax(0, 96px) minmax(0, 84px)', gap: '0 12px', padding: '7px 16px 6px', borderBottom: '1px solid var(--x-hairline)', fontSize: '10px', letterSpacing: '0.1em', color: 'var(--x-caption)' }}>
              <span>GROUP</span><span>SURFACE</span><span>GATE</span><span style={{ textAlign: 'right' }}>STATE</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '4px 16px 14px' }}>
              {(toolRows ?? []).map((t: any, i: number) => (
                <div key={i}>
                  {(t.heading) ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 0 5px' }}>
                      <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: t.dot }}>{t.heading}</span>
                      <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                    </div>
                  ) : null}
                  <div style={{ display: 'grid', gridTemplateColumns: 'minmax(84px, 146px) minmax(0, 1fr) minmax(0, 96px) minmax(0, 84px)', gap: '0 12px', alignItems: 'baseline', padding: '3px 0', borderBottom: '1px solid var(--x-divider)' }}>
                    <span style={{ display: 'flex', alignItems: 'baseline', gap: '7px', fontSize: '12.5px', color: 'var(--x-title)' }}><span style={{ fontSize: '10px', color: t.dot }}>●</span>{t.name}</span>
                    <span style={{ fontSize: '12px', color: 'var(--x-secondary)' }}>{t.sub}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{t.gate}</span>
                    <span style={{ fontSize: '11.5px', color: t.stateFg, textAlign: 'right' }}>{t.right}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : null}

        {(isMcp) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px', fontFamily: '\'JetBrains Mono\', monospace' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/plugins · /reload-mcp</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>2 connected · 1 idle · 3 plugins</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>servers are explicit, never discovered{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px' }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(258px, 1fr))', gap: '10px' }}>
                {(servers ?? []).map((v: any, i: number) => (
                  <div key={i} style={{ border: `1px solid ${v.border}`, background: v.ground, borderRadius: '8px', padding: '12px', display: 'flex', flexDirection: 'column', gap: '10px', fontFamily: '\'JetBrains Mono\', monospace' }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                      <span style={{ fontSize: '11px', color: v.dot }}>●</span>
                      <span style={{ fontSize: '13px', color: 'var(--x-strong)' }}>{v.name}</span>
                      <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: v.dot }}>{v.state}</span>
                    </div>
                    <div style={{ display: 'flex', gap: '14px', fontSize: '11.5px' }}>
                      <span style={{ color: 'var(--x-secondary)' }}>{v.transport}</span>
                      <span style={{ marginLeft: 'auto', color: 'var(--x-numeric)' }}>{v.tools}</span>
                    </div>
                    <div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10.5px', color: 'var(--x-caption)', paddingBottom: '3px' }}>
                        <span>handshake</span><span>{v.handshake}</span>
                      </div>
                      <div style={{ height: '4px', background: 'var(--x-hairline)', borderRadius: '2px', overflow: 'hidden' }}>
                        <div style={{ width: v.bar, height: '100%', background: v.dot }}></div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '20px 0 6px' }}>PLUGINS · 3</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', fontFamily: '\'JetBrains Mono\', monospace' }}>
                {(plugins ?? []).map((p: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '9px', padding: '4px 0', borderBottom: '1px solid var(--x-divider)' }}>
                    <span style={{ fontSize: '10px', color: 'var(--x-done)' }}>●</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)', width: '160px' }}>{p.name}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-secondary)' }}>{p.sub}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>loaded</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}

        {(isAgentDefs) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>.agents/</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>7 definitions · Bun-loaded YAML</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>policy is inherited, not repeated{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px' }}>
              {(tree ?? []).map((n: any, i: number) => (
                <div key={i} style={{ display: 'grid', gridTemplateColumns: '1fr 118px 128px', gap: '12px', alignItems: 'baseline', padding: '5px 0', borderBottom: '1px solid var(--x-divider)' }}>
                  <span style={{ display: 'flex', alignItems: 'baseline', gap: '0' }}>
                    <span style={{ color: 'var(--x-separator)', whiteSpace: 'pre', fontSize: '12.5px' }}>{n.branch}</span>
                    <span style={{ fontSize: '10px', color: n.dot, paddingRight: '7px' }}>●</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{n.name}</span>
                    <span style={{ fontSize: '12px', color: 'var(--x-secondary)', paddingLeft: '10px' }}>{n.sub}</span>
                  </span>
                  <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{n.tools}</span>
                  <span style={{ fontSize: '11.5px', color: n.policyFg }}>{n.policy}</span>
                </div>
              ))}
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '16px', maxWidth: '70ch', textWrap: 'pretty', fontFamily: 'var(--font-body)' }}>Delegation keeps the critical path in the main agent: greetings, simple questions, one-step changes and tightly coupled edits are never delegated.</div>
            </div>
          </div>
        ) : null}

        {(isCron) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/cron</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>3 jobs · 1 disabled · daemon-owned</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>same policy and tool boundaries as the TUI{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', letterSpacing: '0.08em', color: 'var(--x-caption)', padding: '0 11px 5px 164px' }}>
                {(hourTicks ?? []).map((h: any, i: number) => (
                  <span key={i}>{h.label}</span>
                ))}
              </div>
              {(jobs ?? []).map((j: any, i: number) => (
                <div key={i} style={{ border: `1px solid ${j.border}`, background: j.ground, borderRadius: '8px', padding: '9px 11px', marginBottom: '7px' }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '9px' }}>
                    <span style={{ width: '144px', flex: '0 0 144px', display: 'flex', alignItems: 'baseline', gap: '7px' }}>
                      <span style={{ fontSize: '10px', color: j.dot }}>●</span>
                      <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{j.name}</span>
                    </span>
                    <span style={{ flex: '1 1 auto', position: 'relative', height: '18px', borderLeft: '1px solid var(--x-hairline)', borderRight: '1px solid var(--x-hairline)' }}>
                      <span style={{ position: 'absolute', left: '0', right: '0', top: '8px', height: '1px', background: 'var(--x-divider)', display: 'block' }}></span>
                      {(j.marks ?? []).map((m: any, i: number) => (
                        <span key={i} style={{ position: 'absolute', top: '4px', left: m.at, width: '3px', height: '9px', borderRadius: '1px', background: m.color, display: 'block' }}></span>
                      ))}
                    </span>
                  </div>
                  <div style={{ display: 'flex', gap: '14px', padding: '7px 0 0 151px', fontSize: '11.5px', flexWrap: 'wrap' }}>
                    <span style={{ color: 'var(--x-numeric)', whiteSpace: 'nowrap' }}>{j.schedule}</span>
                    <span style={{ color: j.lastFg, whiteSpace: 'nowrap' }}>{j.last}</span>
                    <span style={{ marginLeft: 'auto', color: 'var(--x-secondary)' }}>{j.next}</span>
                  </div>
                </div>
              ))}
            </div>
            <div style={{ borderTop: '1px solid var(--x-hairline)', padding: '7px 16px', display: 'flex', gap: '14px', fontSize: '10.5px', color: 'var(--x-caption)' }}>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>⏎</span> run now</span>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>d</span> disable</span>
              <span><span style={{ color: 'var(--x-meta)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>n</span> new job</span>
            </div>
          </div>
        ) : null}

        {(isPermissions) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/permissions</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>accept-all · 4 static denials</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>static denials outrank every mode{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px' }}>
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>CEILINGS · mode × capability</div>
              <div style={{ display: 'grid', gridTemplateColumns: 'minmax(88px, 148px) repeat(4, minmax(0, 1fr))', gap: '0', border: '1px solid var(--x-hairline)', borderRadius: '8px', overflow: 'hidden' }}>
                <div style={{ padding: '7px 10px', fontSize: '10px', letterSpacing: '0.08em', color: 'var(--x-caption)', background: 'var(--x-chrome)' }}>CAPABILITY</div>
                {(matrixModes ?? []).map((m: any, i: number) => (
                  <div key={i} style={{ padding: '7px 10px', fontSize: '11px', color: m.fg, background: 'var(--x-chrome)', borderLeft: '1px solid var(--x-divider)' }}>{m.name}</div>
                ))}
                {(matrix ?? []).map((row: any, i: number) => (
                  <div key={i} style={{ display: 'contents' }}>
                    <div style={{ padding: '6px 10px', fontSize: '12px', color: 'var(--x-prose)', borderTop: '1px solid var(--x-divider)' }}>{row.name}</div>
                    {(row.cells ?? []).map((c: any, i: number) => (
                      <div key={i} style={{ padding: '6px 10px', borderTop: '1px solid var(--x-divider)', borderLeft: '1px solid var(--x-divider)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ fontSize: '11px', color: c.fg }}>{c.glyph}</span>
                        <span style={{ fontSize: '11px', color: 'var(--x-numeric)' }}>{c.label}</span>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-failed)', padding: '20px 0 7px' }}>STATIC DENIALS · 4 — not grantable by any mode</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1px' }}>
                {(denials ?? []).map((d: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '9px', padding: '5px 10px', border: '1px solid var(--x-failed-border)', background: 'var(--x-failed-bg)', borderRadius: '6px' }}>
                    <span style={{ fontSize: '10px', color: 'var(--x-failed)' }}>●</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{d.name}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-failed-text)' }}>{d.sub}</span>
                    <span style={{ fontSize: '11px', color: 'var(--x-numeric)' }}>deny</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}

        {(isMemory) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>memory</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>4 tiers · 1,284 entries</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>promotion is what empties the working tier{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px' }}>
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '10px' }}>TIERS · 4</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '11px' }}>
                {(tiers ?? []).map((t: any, i: number) => (
                  <div key={i}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '9px', paddingBottom: '4px' }}>
                      <span style={{ fontSize: '10px', color: t.dot }}>●</span>
                      <span style={{ fontSize: '12.5px', color: 'var(--x-title)', width: '96px' }}>{t.name}</span>
                      <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-secondary)' }}>{t.sub}</span>
                      <span style={{ fontSize: '11.5px', color: 'var(--x-numeric)' }}>{t.count}</span>
                    </div>
                    <div style={{ height: '5px', background: 'var(--x-hairline)', borderRadius: '3px', overflow: 'hidden' }}>
                      <div style={{ width: t.bar, height: '100%', background: t.dot }}></div>
                    </div>
                    {(t.cap) ? (
                      <div style={{ fontSize: '10.5px', color: 'var(--x-caption)', paddingTop: '3px' }}>{t.cap}</div>
                    ) : null}
                  </div>
                ))}
              </div>
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '22px 0 8px' }}>RETRIEVAL WEIGHTS</div>
              <div style={{ display: 'flex', height: '10px', borderRadius: '5px', overflow: 'hidden', border: '1px solid var(--x-hairline)' }}>
                {(weights ?? []).map((w: any, i: number) => (
                  <div key={i} style={{ width: w.bar, background: w.color }}></div>
                ))}
              </div>
              <div style={{ display: 'flex', gap: '16px', paddingTop: '8px', flexWrap: 'wrap' }}>
                {(weights ?? []).map((w: any, i: number) => (
                  <span key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11.5px', color: 'var(--x-secondary)', whiteSpace: 'nowrap' }}>
                    <span style={{ width: '8px', height: '8px', borderRadius: '2px', background: w.color, display: 'block' }}></span>{w.label}
                  </span>
                ))}
              </div>
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '10px', maxWidth: '70ch', fontFamily: 'var(--font-body)', textWrap: 'pretty' }}>Hybrid ranking blends a hash-semantic score, BM25 and recency; the weights normalise, so raising one lowers the rest rather than inflating every score.</div>
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '22px 0 8px' }}>WORKSPACE FILES · 3</div>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                {(memFiles ?? []).map((f: any, i: number) => (
                  <div key={i} style={{ border: '1px solid var(--x-hairline)', background: 'var(--x-card)', borderRadius: '8px', padding: '9px 11px', minWidth: '176px' }}>
                    <div style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{f.name}</div>
                    <div style={{ fontSize: '11.5px', color: 'var(--x-secondary)', paddingTop: '2px' }}>{f.sub}</div>
                  </div>
                ))}
              </div>
              <div style={{ border: '1px solid var(--x-needs-border)', background: 'var(--x-needs-bg)', borderRadius: '8px', padding: '10px 12px', marginTop: '18px' }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                  <span style={{ fontSize: '10px', color: 'var(--x-needs)' }}>●</span>
                  <span style={{ fontSize: '12.5px', color: 'var(--x-needs-text)' }}>/remove-memory wipes every tier after confirmation. /remove-history wipes saved chats and snapshots. Neither is reversible.</span>
                </div>
              </div>
            </div>
          </div>
        ) : null}

        {(isHistory) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>session history</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>daemon:8f21c4 · 3 snapshots</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>compaction never flattens the history{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '16px' }}>
              {(timeline ?? []).map((t: any, i: number) => (
                <div key={i} style={{ display: 'flex', gap: '12px' }}>
                  <div style={{ width: '76px', flex: '0 0 76px', textAlign: 'right', fontSize: '11.5px', color: 'var(--x-numeric)', paddingTop: '1px' }}>{t.when}</div>
                  <div style={{ width: '13px', flex: '0 0 13px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                    <span style={{ fontSize: '11px', color: t.dot, lineHeight: '1' }}>{t.glyph}</span>
                    <span style={{ flex: '1 1 auto', width: '1px', background: 'var(--x-hairline)', display: 'block', minHeight: '26px' }}></span>
                  </div>
                  <div style={{ flex: '1 1 auto', paddingBottom: '14px' }}>
                    <div style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{t.name}</div>
                    <div style={{ fontSize: '12px', color: t.subFg, paddingTop: '1px' }}>{t.sub}</div>
                  </div>
                  <div style={{ fontSize: '11.5px', color: 'var(--x-numeric)', paddingTop: '1px' }}>{t.tokens}</div>
                </div>
              ))}
              <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '8px 0 8px 101px' }}>OPERATIONS · 6</div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(232px, 1fr))', gap: '6px', paddingLeft: '101px' }}>
                {(ops ?? []).map((o: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '8px', border: '1px solid var(--x-hairline)', background: 'var(--x-card)', borderRadius: '6px', padding: '6px 9px' }}>
                    <span style={{ fontSize: '12px', color: 'var(--x-working)' }}>{o.name}</span>
                    <span style={{ fontSize: '11.5px', color: 'var(--x-secondary)' }}>{o.sub}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}

        {(isStatus) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>xerxes doctor</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>11 checks · 1 warning</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>reports only what it actually ran{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px' }}>
              <div style={{ border: '1px solid var(--x-needs-border)', background: 'var(--x-needs-bg)', borderRadius: '8px', padding: '12px 14px', display: 'flex', alignItems: 'center', gap: '14px' }}>
                <span style={{ fontSize: '15px', color: 'var(--x-needs)' }}>●</span>
                <div style={{ flex: '1 1 auto' }}>
                  <div style={{ fontSize: '13px', color: 'var(--x-needs-text)' }}>Usable, with one warning</div>
                  <div style={{ fontSize: '12px', color: 'var(--x-secondary)', paddingTop: '2px' }}>The ollama profile will fail on its first turn until the backend is running.</div>
                </div>
                <div style={{ display: 'flex', gap: '12px', fontSize: '11.5px' }}>
                  <span style={{ color: 'var(--x-done)' }}>10 ok</span>
                  <span style={{ color: 'var(--x-needs)' }}>1 warn</span>
                  <span style={{ color: 'var(--x-numeric)' }}>0 fail</span>
                </div>
              </div>
              {(checks ?? []).map((c: any, i: number) => (
                <div key={i}>
                  {(c.heading) ? (
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '16px 0 5px' }}>
                      <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)' }}>{c.heading}</span>
                      <span style={{ flex: '1 1 auto', height: '1px', background: 'linear-gradient(90deg, var(--x-hairline), transparent)' }}></span>
                    </div>
                  ) : null}
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '4px 2px', borderBottom: '1px solid var(--x-divider)' }}>
                    <span style={{ fontSize: '11px', color: c.dot, width: '10px' }}>{c.glyph}</span>
                    <span style={{ fontSize: '12.5px', color: 'var(--x-title)', width: '170px' }}>{c.name}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-secondary)' }}>{c.sub}</span>
                    <span style={{ fontSize: '11.5px', color: c.dot }}>{c.right}</span>
                  </div>
                  {(c.line) ? (
                    <div style={{ fontSize: '12px', color: c.lineFg, padding: '4px 0 4px 20px' }}>{c.line}</div>
                  ) : null}
                </div>
              ))}
            </div>
          </div>
        ) : null}

        {(isChannels) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>channels &amp; surfaces</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>5 callers · one turn loop</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>no surface starts a second runtime{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '18px 16px' }}>
              <div style={{ display: 'flex', alignItems: 'stretch', flexWrap: 'wrap', gap: '12px 0' }}>
                <div style={{ flex: '1 1 190px', minWidth: '166px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                  {(callers ?? []).map((c: any, i: number) => (
                    <div key={i} style={{ border: `1px solid ${c.border}`, background: c.ground, borderRadius: '8px', padding: '8px 10px' }}>
                      <div style={{ display: 'flex', alignItems: 'baseline', gap: '7px' }}>
                        <span style={{ fontSize: '10px', color: c.dot }}>●</span>
                        <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{c.name}</span>
                        <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: c.dot }}>{c.state}</span>
                      </div>
                      <div style={{ fontSize: '11px', color: 'var(--x-secondary)', paddingLeft: '17px' }}>{c.sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ width: '34px', flex: '0 0 34px', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '0', right: '0', top: '50%', height: '1px', background: 'var(--x-hairline)', display: 'block' }}></span>
                  <span style={{ position: 'absolute', left: '50%', top: '12%', bottom: '12%', width: '1px', background: 'var(--x-hairline)', display: 'block' }}></span>
                  <span style={{ position: 'relative', fontSize: '11px', color: 'var(--x-working)', background: 'var(--x-screen)', padding: '2px 3px' }}>→</span>
                </div>
                <div style={{ flex: '1 1 240px', minWidth: '150px', border: '1px solid var(--x-focus)', background: 'var(--x-working-bg)', borderRadius: '8px', padding: '14px' }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                    <span style={{ fontSize: '11px', color: 'var(--x-working)' }}>●</span>
                    <span style={{ fontSize: '13px', color: 'var(--x-strong)' }}>Bun daemon</span>
                    <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-working)' }}>v35 · running</span>
                  </div>
                  <div style={{ fontSize: '11.5px', color: 'var(--x-secondary)', padding: '3px 0 10px 19px' }}>project-scoped socket · NDJSON JSON-RPC</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '3px', paddingLeft: '19px' }}>
                    {(daemonOwns ?? []).map((d: any, i: number) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '8px', fontSize: '12px' }}>
                        <span style={{ color: 'var(--x-separator)' }}>└</span>
                        <span style={{ color: 'var(--x-prose)' }}>{d.text}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              <div style={{ fontSize: '12.5px', color: 'var(--x-meta)', paddingTop: '18px', maxWidth: '76ch', fontFamily: 'var(--font-body)', textWrap: 'pretty' }}>Every caller consumes the same serializable turn contract. The TUI does not own model calls, persistence or workspace execution, and the daemon guarantees a terminal event for every turn across all of them.</div>
            </div>
          </div>
        ) : null}

        {(isHelp) ? (
          <div style={{ flex: '1 1 auto', minHeight: '0', display: 'flex', flexDirection: 'column', fontFamily: '\'JetBrains Mono\', monospace' }}>
            <div style={{ padding: '10px 16px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '10px' }}>
              <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>/help</span>
              <span style={{ fontSize: '11px', color: 'var(--x-meta)' }}>live catalogue · plugins and skills extend it</span>
              <span style={{ marginLeft: 'auto', fontSize: '10.5px', color: 'var(--x-caption)' }}>keyboard complete; the mouse is additive{mark1}</span>
            </div>
            <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '14px 16px', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(258px, 1fr))', gap: '26px', alignContent: 'start' }}>
              <div>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>KEYBOARD</div>
                {(helpKeys ?? []).map((k: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '3px 0' }}>
                    <span style={{ minWidth: '34px', textAlign: 'center', fontSize: '11px', color: 'var(--x-title)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 5px' }}>{k.key}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12.5px', color: 'var(--x-secondary)' }}>{k.label}</span>
                  </div>
                ))}
              </div>
              <div>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', paddingBottom: '8px' }}>COMMANDS</div>
                {(helpCommands ?? []).map((c: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '10px', padding: '3px 0' }}>
                    <span style={{ width: '100px', fontSize: '12px', color: 'var(--x-working)' }}>{c.key}</span>
                    <span style={{ flex: '1 1 auto', fontSize: '12.5px', color: 'var(--x-secondary)' }}>{c.label}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}

      </div>

      {(railOpen) ? (
        <div style={{ width: '286px', flex: '0 0 286px', borderLeft: '1px solid var(--x-hairline)', background: 'var(--x-chrome)', display: 'flex', flexDirection: 'column', overflow: 'hidden', fontFamily: '\'JetBrains Mono\', monospace' }}>
          <div style={{ padding: '9px 12px', borderBottom: '1px solid var(--x-divider)', display: 'flex', alignItems: 'baseline', gap: '8px' }}>
            <span style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-secondary)' }}>{railTitle}</span>
            <span style={{ marginLeft: 'auto', fontSize: '10px', color: 'var(--x-numeric)', border: '1px solid var(--x-hairline)', borderRadius: '4px', padding: '1px 4px' }}>{railKey}</span>
          </div>
          <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '8px 10px' }}>
            {(railIsInspector) ? (
              <div>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: '8px' }}>
                  <span style={{ fontSize: '11px', color: agent.dot }}>●</span>
                  <span style={{ fontSize: '12.5px', color: 'var(--x-title)' }}>{agent.name}</span>
                </div>
                <div style={{ fontSize: '12px', color: 'var(--x-secondary)', padding: '2px 0 8px 19px' }}>{agent.task}</div>
                <div style={{ fontSize: '12px', color: agent.lineFg, paddingLeft: '19px' }}>{agent.line}</div>
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '14px 0 6px' }}>TOOL CALLS · {agent.toolCount}</div>
                {(agent.calls ?? []).map((c: any, i: number) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'baseline', gap: '7px', fontSize: '12px', padding: '1px 0' }}>
                    <span style={{ color: c.dot }}>⏺</span>
                    <span style={{ color: 'var(--x-secondary)' }}>{c.verb}</span>
                    <span style={{ flex: '1 1 auto', color: 'var(--x-leader)', overflow: 'hidden', whiteSpace: 'nowrap' }}>{c.leader}</span>
                    <span style={{ color: 'var(--x-numeric)' }}>{c.dur}</span>
                  </div>
                ))}
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '14px 0 6px' }}>FILES TOUCHED</div>
                {(agent.files ?? []).map((f: any, i: number) => (
                  <div key={i} style={{ fontSize: '12px', color: 'var(--x-prose)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', direction: 'rtl', textAlign: 'left' }}>{f.path}</div>
                ))}
                <div style={{ fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-caption)', padding: '14px 0 6px' }}>POLICY</div>
                <div style={{ fontSize: '12px', color: 'var(--x-secondary)' }}>{agent.policy}</div>
              </div>
            ) : null}
            {(railIsFleet) ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '3px' }}>
                {(railRows ?? []).map((a: any, i: number) => (
                  <div key={i} onClick={a.pick} style={{ border: `1px solid ${a.border}`, background: a.ground, borderLeft: `3px solid ${a.rail}`, borderRadius: '8px', padding: '6px 8px', cursor: 'pointer' }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: '7px' }}>
                      <span style={{ fontSize: '11px', color: a.dot }}>●</span>
                      <span style={{ flex: '1 1 auto', fontSize: '12px', color: 'var(--x-title)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{a.name}</span>
                    </div>
                    <div style={{ fontSize: '11.5px', color: 'var(--x-numeric)', paddingLeft: '18px' }}>{a.budget}</div>
                  </div>
                ))}
              </div>
            ) : null}
          </div>
          <div style={{ borderTop: '1px solid var(--x-divider)', padding: '7px 12px', fontSize: '10.5px', color: 'var(--x-caption)' }}>{railFoot}</div>
        </div>
      ) : null}

      {(callouts) ? (
        <div style={{ width: '196px', flex: '0 0 196px', borderLeft: '1px solid var(--x-hairline)', background: 'var(--x-sunken)', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <div style={{ padding: '9px 12px', borderBottom: '1px solid var(--x-divider)', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.1em', color: 'var(--x-secondary)' }}>NOTES</div>
          <div style={{ flex: '1 1 auto', minHeight: '0', overflowY: 'auto', padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {(notes ?? []).map((n: any, i: number) => (
              <div key={i}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: '6px' }}>
                  <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: 'var(--x-needs)' }}>{n.mark}</span>
                  <span style={{ fontFamily: '\'JetBrains Mono\', monospace', fontSize: '10.5px', letterSpacing: '0.06em', color: 'var(--x-secondary)' }}>{n.row}</span>
                </div>
                <div style={{ fontSize: '12px', lineHeight: '1.5', color: 'var(--x-menubar-meta)', paddingTop: '3px', textWrap: 'pretty' }}>{n.text}</div>
              </div>
            ))}
          </div>
        </div>
      ) : null}

    </div>

    <div style={{ height: '28px', flex: '0 0 28px', display: 'flex', alignItems: 'center', gap: '10px', padding: '0 14px', background: 'var(--x-screen)', borderTop: '1px solid var(--x-hairline)', fontFamily: '\'JetBrains Mono\', monospace', fontSize: '11px', color: 'var(--x-meta)' }}>
      <span style={{ color: 'var(--x-working)' }}>✦</span>
      <span style={{ color: 'var(--x-secondary)' }}>~/src/Xerxes-Agents</span>
      <span style={{ color: 'var(--x-rule)' }}>│</span>
      <span>{statusModel}</span>
      <span style={{ color: 'var(--x-rule)' }}>│</span>
      <span style={{ color: 'var(--x-working)' }}>◆</span><span>{modeLabel}</span>
      <span style={{ color: 'var(--x-rule)' }}>│</span>
      <span style={{ color: permFg }}>{permLabel}</span>
      <span style={{ color: 'var(--x-rule)' }}>│</span>
      <span>{contextLabel}</span>
      <span style={{ marginLeft: 'auto', color: 'var(--x-caption)' }}>{statusRight}</span>
    </div>
  </div>
</div></>
  )
}
