// Copyright 2026 The Xerxes-Agents Author @erfanzar (Erfan Zare Chavoshi).
// Licensed under the Apache License, Version 2.0.

import { dependencyLayers, stableIdentifier } from './task.js'
import { directXmlChildren, parseXmlRoot, xmlChild, xmlIdentifiers, xmlText, type XmlElement } from './xml.js'

export type PlanComplexity = 'high' | 'low' | 'medium'
export type PlanStepStatus = 'failed' | 'pending' | 'skipped' | 'succeeded'

export interface PlanStep {
  readonly action: string
  readonly agentId?: string
  readonly arguments: Readonly<Record<string, string>>
  readonly dependencies: readonly string[]
  readonly description: string
  readonly id: string
}

export interface ExecutionPlan {
  readonly complexity: PlanComplexity
  readonly estimatedMinutes: number
  readonly id: string
  readonly objective: string
  readonly steps: readonly PlanStep[]
}

export interface PlanGenerationRequest {
  readonly agents?: readonly PlanAgentDescription[]
  readonly context?: string
  readonly objective: string
}

export interface PlanAgentDescription {
  readonly id: string
  readonly role?: string
  readonly summary?: string
}

export interface PlanCreationResult {
  readonly error?: string
  readonly plan: ExecutionPlan
  readonly usedFallback: boolean
}

export type PlanGenerator = (request: PlanGenerationRequest) => string | Promise<string>

export interface PlanStepExecutionRequest {
  readonly arguments: Readonly<Record<string, string>>
  readonly dependencyOutputs: ReadonlyMap<string, PlanStepOutput>
  readonly objective: string
  readonly step: PlanStep
}

export type PlanStepExecutor = (request: PlanStepExecutionRequest) => string | PlanStepExecutionResult | Promise<string | PlanStepExecutionResult>

export interface PlanStepExecutionResult {
  readonly metadata?: Readonly<Record<string, unknown>>
  readonly output: string
}

export interface PlanStepOutput {
  readonly completedAt: Date
  readonly durationMs: number
  readonly error?: string
  readonly metadata: Readonly<Record<string, unknown>>
  readonly output: string
  readonly startedAt: Date
  readonly status: Exclude<PlanStepStatus, 'pending'>
  readonly stepId: string
}

export interface PlanExecutionResult {
  readonly outputs: readonly PlanStepOutput[]
  readonly rawOutput: string
}

export interface PlanExecutionOptions {
  readonly now?: () => Date
  readonly parallel?: boolean
}

/** Parse a constrained XML execution plan generated by an injected planning agent. */
export function parseExecutionPlan(response: string, fallbackObjective: string): ExecutionPlan {
  const root = parseXmlRoot(response, 'plan')
  const children = directXmlChildren(root.inner)
  const objective = xmlText(xmlChild(children, 'objective'), fallbackObjective) || fallbackObjective
  const complexity = parseComplexity(xmlText(xmlChild(children, 'complexity'), 'medium'))
  const estimatedMinutes = parseMinutes(xmlText(xmlChild(children, 'estimated_time'), '0'))
  const steps = children.filter(child => child.name === 'step').map(parsePlanStep)
  if (steps.length === 0) throw new Error('Execution plan must contain at least one <step>')
  const plan: ExecutionPlan = {
    id: stableIdentifier('plan', objective),
    objective,
    complexity,
    estimatedMinutes,
    steps,
  }
  validateExecutionPlan(plan)
  return plan
}

/** Return a usable single-step plan when a planner response is unavailable or invalid. */
export function fallbackExecutionPlan(objective: string, agentId?: string): ExecutionPlan {
  const step: PlanStep = {
    id: '1',
    action: 'execute_objective',
    description: objective,
    arguments: { objective },
    dependencies: [],
    ...(agentId ? { agentId } : {}),
  }
  return {
    id: stableIdentifier('fallback-plan', objective),
    objective,
    complexity: 'low',
    estimatedMinutes: 0,
    steps: [step],
  }
}

/** Validate plan step IDs and return stable dependency layers. */
export function planDependencyLayers(plan: ExecutionPlan): PlanStep[][] {
  return dependencyLayers(plan.steps, step => step.id, step => step.dependencies, 'plan step')
}

export function validateExecutionPlan(plan: ExecutionPlan): void {
  if (!plan.objective.trim()) throw new Error('Plan objective cannot be empty')
  if (!Number.isFinite(plan.estimatedMinutes) || plan.estimatedMinutes < 0) {
    throw new Error('Plan estimatedMinutes must be a non-negative number')
  }
  planDependencyLayers(plan)
}

/** Return steps eligible to run after completed steps, excluding branches blocked by failures. */
export function getNextPlanSteps(
  plan: ExecutionPlan,
  completed: ReadonlySet<string>,
  failed: ReadonlySet<string> = new Set(),
): PlanStep[] {
  validateExecutionPlan(plan)
  return plan.steps.filter(step => !completed.has(step.id) && !failed.has(step.id)
    && !step.dependencies.some(dependency => failed.has(dependency))
    && step.dependencies.every(dependency => completed.has(dependency)))
}

/** Resolve result_from_step_N placeholders before a step is dispatched. */
export function resolvePlanArguments(
  argumentsValue: Readonly<Record<string, string>>,
  outputs: ReadonlyMap<string, PlanStepOutput>,
): Readonly<Record<string, string>> {
  const resolved: Record<string, string> = {}
  for (const [key, value] of Object.entries(argumentsValue)) {
    const exact = /^result_from_step_(.+)$/.exec(value)
    if (exact?.[1]) {
      resolved[key] = outputs.get(exact[1])?.output ?? value
      continue
    }
    resolved[key] = value.replace(/\{\{result_from_step_([^}]+)\}\}/g, (_whole, id: string) => outputs.get(id)?.output ?? _whole)
  }
  return resolved
}

/** Execute a plan with an injected step executor. Failures skip only downstream steps. */
export async function executeExecutionPlan(
  plan: ExecutionPlan,
  executor: PlanStepExecutor,
  options: PlanExecutionOptions = {},
): Promise<PlanExecutionResult> {
  validateExecutionPlan(plan)
  const now = options.now ?? (() => new Date())
  const states = new Map<string, PlanStepStatus>(plan.steps.map(step => [step.id, 'pending']))
  const outputs = new Map<string, PlanStepOutput>()

  while ([...states.values()].some(status => status === 'pending')) {
    let stateChanged = false
    for (const step of plan.steps) {
      if (states.get(step.id) !== 'pending') continue
      if (!step.dependencies.some(dependency => {
        const status = states.get(dependency)
        return status === 'failed' || status === 'skipped'
      })) continue
      const timestamp = now()
      outputs.set(step.id, {
        stepId: step.id,
        status: 'skipped',
        output: '',
        error: 'A dependency did not complete successfully',
        startedAt: timestamp,
        completedAt: timestamp,
        durationMs: 0,
        metadata: {},
      })
      states.set(step.id, 'skipped')
      stateChanged = true
    }
    if (stateChanged) continue

    const completed = new Set([...states].flatMap(([id, status]) => status === 'succeeded' ? [id] : []))
    const failed = new Set([...states].flatMap(([id, status]) => status === 'failed' ? [id] : []))
    const ready = getNextPlanSteps(plan, completed, failed).filter(step => states.get(step.id) === 'pending')
    if (ready.length === 0) throw new Error('No executable plan steps remain')
    if (options.parallel) await Promise.all(ready.map(step => executeStep(plan, step, executor, outputs, states, now)))
    else for (const step of ready) await executeStep(plan, step, executor, outputs, states, now)
  }

  const ordered = plan.steps.flatMap(step => {
    const output = outputs.get(step.id)
    return output ? [output] : []
  })
  return {
    outputs: ordered,
    rawOutput: ordered.filter(output => output.status === 'succeeded').at(-1)?.output ?? '',
  }
}

/** Planner facade that keeps planning model-agnostic through a generator function. */
export class CortexPlanner {
  constructor(private readonly generator: PlanGenerator | undefined = undefined) {}

  async createPlan(request: PlanGenerationRequest): Promise<PlanCreationResult> {
    if (!this.generator) {
      return {
        plan: fallbackExecutionPlan(request.objective, request.agents?.[0]?.id),
        usedFallback: true,
        error: 'No plan generator was configured',
      }
    }
    try {
      return { plan: parseExecutionPlan(await this.generator(request), request.objective), usedFallback: false }
    } catch (error) {
      return {
        plan: fallbackExecutionPlan(request.objective, request.agents?.[0]?.id),
        usedFallback: true,
        error: errorMessage(error),
      }
    }
  }

  executePlan(plan: ExecutionPlan, executor: PlanStepExecutor, options: PlanExecutionOptions = {}): Promise<PlanExecutionResult> {
    return executeExecutionPlan(plan, executor, options)
  }
}

function parsePlanStep(element: XmlElement): PlanStep {
  const id = element.attributes.id?.trim()
  if (!id) throw new Error('Every <step> requires a non-empty id attribute')
  const children = directXmlChildren(element.inner)
  const argumentsElement = xmlChild(children, 'arguments')
  const argumentsValue: Record<string, string> = {}
  if (argumentsElement) {
    for (const argument of directXmlChildren(argumentsElement.inner)) {
      if (Object.hasOwn(argumentsValue, argument.name)) throw new Error(`Duplicate argument ${argument.name} in step ${id}`)
      argumentsValue[argument.name] = xmlText(argument)
    }
  }
  const action = xmlText(xmlChild(children, 'action'), 'execute') || 'execute'
  const agentId = xmlText(xmlChild(children, 'agent'))
  return {
    id,
    action,
    description: xmlText(xmlChild(children, 'description'), action) || action,
    arguments: argumentsValue,
    dependencies: xmlIdentifiers(xmlChild(children, 'dependencies')),
    ...(agentId ? { agentId } : {}),
  }
}

function parseComplexity(value: string): PlanComplexity {
  const normalized = value.trim().toLowerCase()
  return normalized === 'low' || normalized === 'medium' || normalized === 'high' ? normalized : 'medium'
}

function parseMinutes(value: string): number {
  const parsed = Number(value)
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0
}

async function executeStep(
  plan: ExecutionPlan,
  step: PlanStep,
  executor: PlanStepExecutor,
  outputs: Map<string, PlanStepOutput>,
  states: Map<string, PlanStepStatus>,
  now: () => Date,
): Promise<void> {
  const startedAt = now()
  try {
    const result = await executor({
      step,
      objective: plan.objective,
      arguments: resolvePlanArguments(step.arguments, outputs),
      dependencyOutputs: outputs,
    })
    const normalized = typeof result === 'string' ? { output: result } : result
    const completedAt = now()
    outputs.set(step.id, {
      stepId: step.id,
      status: 'succeeded',
      output: normalized.output,
      startedAt,
      completedAt,
      durationMs: Math.max(0, completedAt.getTime() - startedAt.getTime()),
      metadata: normalized.metadata ?? {},
    })
    states.set(step.id, 'succeeded')
  } catch (error) {
    const completedAt = now()
    outputs.set(step.id, {
      stepId: step.id,
      status: 'failed',
      output: '',
      error: errorMessage(error),
      startedAt,
      completedAt,
      durationMs: Math.max(0, completedAt.getTime() - startedAt.getTime()),
      metadata: {},
    })
    states.set(step.id, 'failed')
  }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}
